# Server
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/sport_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=hoan123456


# JPA
# T\u1EA1o b\u1EA3ng trong database
# d\u1EF1a tr\u00EAn c\u00E1c entity
spring.jpa.hibernate.ddl-auto=update

# Hi\u1EC3n th\u1ECB c\u00E1c c\u00E2u l\u1EC7nh sql \u1EDF c\u1EEDa s\u1ED5 console c\u1EE7a intellij
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# S\u1EED d\u1EE5ng \u0111\u00FAng c\u00FA ph\u00E1p SQL trong MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=SportBookingSecretKey2026CongHoanProjectVeryLongSecretKey123456
app.jwt.expiration=86400000

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
